version: '3.5'

services:

  cleevio_postgres:
    container_name: cleevio_database
    image: postgres
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'Password#42'
      PGDATA: /data/postgres
    volumes:
      - cleevio_postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: always


  cleevio_pgadmin:
    container_name: cleevio_pgadmin_container
    image: dpage/pgadmin4:5.0
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-example@example.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
      - cleevio_pgadmin:/root/.pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - postgres

networks:
  postgres:
    driver: bridge

volumes:
  cleevio_postgres:
  cleevio_pgadmin: